pipeline:
  publish-prod-buildx:
    image: woodpeckerci/plugin-docker-buildx
    group: docker
    secrets: [ docker_username, docker_password ]
    settings:
      repo: powermonitoring/backend
      dockerfile: Dockerfile
      platforms: linux/amd64
      auto_tag: true
    when:
      branch: main
      event: push

  deploy:
    image: alpine
    secrets: [ DEPLOY_KEY, SSH_CONFIG, COMPOSE_FILE ]
    commands:
      - apk add openssh rsync
      - mkdir ~/.ssh
      - printf '%s\n' "$${DEPLOY_KEY}" > ~/.ssh/deploy_key
      - printf "$${SSH_CONFIG}" > ~/.ssh/config
      - chmod -R u=rwX,go= ~/.ssh
      - rsync -atv --delete --progress ./docker_compose.yml ci:$${COMPOSE_FILE}
      - ssh ci deploy/pull.sh
      - ssh ci docker compose -f "$${COMPOSE_FILE}" up -d
    when:
      status: [ success ]
      branch:
        include: [ main ]
      event: [ push, deployment ]